name: "Build image"

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: login
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta_app
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=sha,format=long
      - id: build_push
        name: Build and push app Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta_app.outputs.tags }}
          labels: ${{ steps.meta_app.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
    outputs:
      image_id: ${{ steps.build_push.outputs.imageid }}
      image_digest: ${{ steps.build_push.outputs.digest }}
      image_metadata: ${{ steps.build_push.outputs.metadata }}
  deploy_test:
    name: Deploy test
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: write
    needs:
      - build
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test pulling image
        run: docker image pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build.outputs.image_digest }}
      - name: Add tag
        run: docker image tag {{ env.IMAGE_NAME }}@${{ needs.build.outputs.image_digest }} {{ env.IMAGE_NAME }}:testing
      - name: Docker image list
        run: docker image ls --all
