name: "Check a commit"

on:
  push:

jobs:
  dockerfile:
    name: Linter for Dockerfile
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
